/*
 * Created by Jack Darlington | 2023
 */
package com.jackdarlington.studenthub.ui;

import com.jackdarlington.studenthub.entity.AbstractUser;
import com.jackdarlington.studenthub.entity.StaffMember;
import com.jackdarlington.studenthub.entity.Student;
import com.jackdarlington.studenthub.main.Controller;
import com.jackdarlington.studenthub.main.Model;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Jack
 */
public class SessionUI extends javax.swing.JFrame {
    
    private static Font logoFont;
    private Font buttonFont;
    private Font titleFont;

    /**
     * Creates new form SessionUI
     */
    public SessionUI() {
        GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        try {
            logoFont = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/fonts/DarumadropOne-Regular.ttf"));
            genv.registerFont(logoFont);
            logoFont = logoFont.deriveFont(24f);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(LogInUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            buttonFont = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/fonts/Rubik-SemiBold.ttf"));
            genv.registerFont(buttonFont);
            buttonFont = buttonFont.deriveFont(16f);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(LogInUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            titleFont = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/fonts/Poppins-SemiBold.ttf"));
            genv.registerFont(titleFont);
            titleFont = titleFont.deriveFont(52f);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(LogInUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        cancelButtonLogoutDialog = new javax.swing.JButton();
        logoutButtonLogoutDialog = new javax.swing.JButton();
        toolbarPanel = new javax.swing.JPanel();
        studentHubLogo = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        personalDetailsButton = new javax.swing.JButton();
        academicDetailsButton = new javax.swing.JButton();
        enrolmentButton = new javax.swing.JButton();
        gradesButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        contentTabPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        personalDetailsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        personalEmailField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        streetAdd1Field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        streetAdd2Field = new javax.swing.JTextField();
        suburbField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        postCodeField = new javax.swing.JTextField();
        savePersonalDetailsButton = new javax.swing.JButton();
        databaseSaveLabel = new javax.swing.JLabel();
        academicDetailsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enrolmentPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gradePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userProfilePictureLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        studentCourseLabel = new javax.swing.JLabel();
        studentIDLabel = new javax.swing.JLabel();
        myGradesLabel = new javax.swing.JLabel();
        courseProgressBar = new javax.swing.JProgressBar();
        paperLabel1 = new javax.swing.JLabel();

        logoutDialog.setTitle("Log Out");
        logoutDialog.setLocation(new java.awt.Point(0, 0));
        logoutDialog.setMinimumSize(new java.awt.Dimension(250, 100));
        logoutDialog.setResizable(false);

        jLabel2.setText("Are you sure you want to log out?");

        cancelButtonLogoutDialog.setText("Cancel");
        cancelButtonLogoutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonLogoutDialogActionPerformed(evt);
            }
        });

        logoutButtonLogoutDialog.setText("Log Out");
        logoutButtonLogoutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonLogoutDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutDialogLayout = new javax.swing.GroupLayout(logoutDialog.getContentPane());
        logoutDialog.getContentPane().setLayout(logoutDialogLayout);
        logoutDialogLayout.setHorizontalGroup(
            logoutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutDialogLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(logoutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logoutDialogLayout.createSequentialGroup()
                        .addComponent(cancelButtonLogoutDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButtonLogoutDialog))
                    .addComponent(jLabel2))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        logoutDialogLayout.setVerticalGroup(
            logoutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(logoutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonLogoutDialog)
                    .addComponent(logoutButtonLogoutDialog))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        logoutDialog.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("session"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbarPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        toolbarPanel.setMinimumSize(new java.awt.Dimension(200, 600));
        toolbarPanel.setPreferredSize(new java.awt.Dimension(200, 600));

        studentHubLogo.setFont(logoFont);
        studentHubLogo.setText("Student Hub");

        homeButton.setBackground(new Color(0,0,0,0));
        homeButton.setFont(buttonFont);
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        personalDetailsButton.setBackground(new Color(0,0,0,0));
        personalDetailsButton.setFont(buttonFont);
        personalDetailsButton.setText("Personal Details");
        personalDetailsButton.setBorder(null);
        personalDetailsButton.setBorderPainted(false);
        personalDetailsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                personalDetailsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                personalDetailsButtonMouseExited(evt);
            }
        });
        personalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalDetailsButtonActionPerformed(evt);
            }
        });

        academicDetailsButton.setBackground(new Color(0,0,0,0));
        academicDetailsButton.setFont(buttonFont);
        academicDetailsButton.setText("Academic Details");
        academicDetailsButton.setBorder(null);
        academicDetailsButton.setBorderPainted(false);
        academicDetailsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        academicDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                academicDetailsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                academicDetailsButtonMouseExited(evt);
            }
        });
        academicDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academicDetailsButtonActionPerformed(evt);
            }
        });

        enrolmentButton.setBackground(new Color(0,0,0,0));
        enrolmentButton.setFont(buttonFont);
        enrolmentButton.setText("Enrolment");
        enrolmentButton.setBorder(null);
        enrolmentButton.setBorderPainted(false);
        enrolmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enrolmentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enrolmentButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enrolmentButtonMouseExited(evt);
            }
        });
        enrolmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolmentButtonActionPerformed(evt);
            }
        });

        gradesButton.setBackground(new Color(0,0,0,0));
        gradesButton.setFont(buttonFont);
        gradesButton.setText("Grades");
        gradesButton.setBorder(null);
        gradesButton.setBorderPainted(false);
        gradesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gradesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gradesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gradesButtonMouseExited(evt);
            }
        });
        gradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradesButtonActionPerformed(evt);
            }
        });

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog-wheel-silhouette-20px.png"))); // NOI18N
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolbarPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentHubLogo)
                            .addComponent(enrolmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(academicDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(personalDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gradesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(toolbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(settingsButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createSequentialGroup()
                .addComponent(studentHubLogo)
                .addGap(27, 27, 27)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(personalDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(academicDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enrolmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(settingsButton)
                .addContainerGap())
        );

        getContentPane().add(toolbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contentPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        contentPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentTabPane.setMinimumSize(new java.awt.Dimension(800, 635));
        contentTabPane.setPreferredSize(new java.awt.Dimension(800, 635));
        contentTabPane.setRequestFocusEnabled(false);

        homePanel.setBackground(new java.awt.Color(75, 78, 80));
        homePanel.setMinimumSize(new java.awt.Dimension(800, 400));
        homePanel.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel6.setFont(titleFont);
        jLabel6.setForeground(new java.awt.Color(235, 235, 235));
        jLabel6.setText("Home");

        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setText("Welcome back " + Model.loggedInUser.getFirstName());

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        contentTabPane.addTab("Home", null, homePanel, "");

        personalDetailsPanel.setBackground(new java.awt.Color(75, 78, 80));

        jLabel7.setFont(titleFont);
        jLabel7.setForeground(new java.awt.Color(235, 235, 235));
        jLabel7.setText("Personal Details");

        jLabel3.setText("First Name");

        firstNameField.setText("jTextField1");
        firstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameFieldKeyPressed(evt);
            }
        });

        jLabel12.setText("Last Name");

        jLabel13.setText("Email Address");

        personalEmailField.setText("jTextField3");
        personalEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personalEmailFieldKeyPressed(evt);
            }
        });

        jLabel14.setText("Phone Number");

        phoneNumberField.setText("jTextField1");
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyPressed(evt);
            }
        });

        lastNameField.setText("jTextField1");
        lastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyPressed(evt);
            }
        });

        jLabel15.setText("Street Address");

        streetAdd1Field.setText("jTextField1");
        streetAdd1Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                streetAdd1FieldKeyPressed(evt);
            }
        });

        jLabel16.setText("Street Address 2");

        streetAdd2Field.setText("jTextField1");
        streetAdd2Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                streetAdd2FieldKeyPressed(evt);
            }
        });

        suburbField.setText("jTextField1");
        suburbField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                suburbFieldKeyPressed(evt);
            }
        });

        jLabel17.setText("Suburb");

        jLabel18.setText("City");

        cityField.setText("jTextField1");
        cityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityFieldKeyPressed(evt);
            }
        });

        jLabel19.setText("Postcode");

        postCodeField.setText("jTextField1");
        postCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                postCodeFieldKeyPressed(evt);
            }
        });

        savePersonalDetailsButton.setText("Save");
        savePersonalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePersonalDetailsButtonActionPerformed(evt);
            }
        });

        firstNameField.setText(Model.loggedInUser.getFirstName());
        personalEmailField.setText(Model.loggedInUser.userData.get("Personal Email"));
        phoneNumberField.setText(Model.loggedInUser.userData.get("Phone Number"));
        lastNameField.setText(Model.loggedInUser.getLastName());
        streetAdd1Field.setText(Model.loggedInUser.userData.get("Street Address 1"));
        streetAdd2Field.setText(Model.loggedInUser.userData.get("Street Address 2"));
        suburbField.setText(Model.loggedInUser.userData.get("Suburb"));
        cityField.setText(Model.loggedInUser.userData.get("City"));
        postCodeField.setText(Model.loggedInUser.userData.get("Post Code"));

        javax.swing.GroupLayout personalDetailsPanelLayout = new javax.swing.GroupLayout(personalDetailsPanel);
        personalDetailsPanel.setLayout(personalDetailsPanelLayout);
        personalDetailsPanelLayout.setHorizontalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(databaseSaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(savePersonalDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personalEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetAdd1Field)
                                    .addComponent(streetAdd2Field)
                                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))
                            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(cityField))
                                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(suburbField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(postCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        personalDetailsPanelLayout.setVerticalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(personalEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(streetAdd1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(streetAdd2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(suburbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(postCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePersonalDetailsButton)
                    .addComponent(databaseSaveLabel))
                .addGap(20, 20, 20))
        );

        contentTabPane.addTab("tab2", personalDetailsPanel);

        academicDetailsPanel.setBackground(new java.awt.Color(75, 78, 80));

        jLabel8.setFont(titleFont);
        jLabel8.setForeground(new java.awt.Color(235, 235, 235));
        jLabel8.setText("Academic Details");

        jLabel4.setForeground(new java.awt.Color(235, 235, 235));
        jLabel4.setText("Welcome back " + Model.loggedInUser.getFirstName());

        javax.swing.GroupLayout academicDetailsPanelLayout = new javax.swing.GroupLayout(academicDetailsPanel);
        academicDetailsPanel.setLayout(academicDetailsPanelLayout);
        academicDetailsPanelLayout.setHorizontalGroup(
            academicDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(academicDetailsPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(academicDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(academicDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 289, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        academicDetailsPanelLayout.setVerticalGroup(
            academicDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(academicDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        contentTabPane.addTab("tab3", academicDetailsPanel);

        enrolmentPanel.setBackground(new java.awt.Color(75, 78, 80));

        jLabel9.setFont(titleFont);
        jLabel9.setForeground(new java.awt.Color(235, 235, 235));
        jLabel9.setText("Enrolments");

        jLabel5.setForeground(new java.awt.Color(235, 235, 235));
        jLabel5.setText("Welcome back " + Model.loggedInUser.getFirstName());

        javax.swing.GroupLayout enrolmentPanelLayout = new javax.swing.GroupLayout(enrolmentPanel);
        enrolmentPanel.setLayout(enrolmentPanelLayout);
        enrolmentPanelLayout.setHorizontalGroup(
            enrolmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolmentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(enrolmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enrolmentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 289, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        enrolmentPanelLayout.setVerticalGroup(
            enrolmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        contentTabPane.addTab("tab4", enrolmentPanel);

        gradePanel.setBackground(new java.awt.Color(75, 78, 80));

        jLabel10.setFont(titleFont);
        jLabel10.setForeground(new java.awt.Color(235, 235, 235));
        jLabel10.setText("Grades");

        jLabel11.setForeground(new java.awt.Color(235, 235, 235));
        jLabel11.setText("Welcome back " + Model.loggedInUser.getFirstName());

        javax.swing.GroupLayout gradePanelLayout = new javax.swing.GroupLayout(gradePanel);
        gradePanel.setLayout(gradePanelLayout);
        gradePanelLayout.setHorizontalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 289, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        gradePanelLayout.setVerticalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        contentTabPane.addTab("tab5", gradePanel);

        contentPanel.add(contentTabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -35, 600, -1));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 600));

        userProfilePictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-silhouette-128px.png"))); // NOI18N

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLabel.setText(Model.loggedInUser.getFirstName() + " " + Model.loggedInUser.getLastName());
        userNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTypeLabel.setText(Model.loggedInUser.getUserType());
        userTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-silhouette-20px.png"))); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        studentCourseLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        studentCourseLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        studentCourseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        studentCourseLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        studentIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentIDLabel.setToolTipText("");

        myGradesLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        courseProgressBar.setForeground(new java.awt.Color(204, 255, 204));
        courseProgressBar.setMaximum(360);
        courseProgressBar.setEnabled(false);
        courseProgressBar.setVisible(false);

        paperLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        paperLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        paperLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        if (Model.loggedInUser.getUserType().equals("Student")) {
            myGradesLabel.setText("My Grades");
        }
        if (Model.loggedInUser.getUserType().equals("Student")) {
            courseProgressBar.setToolTipText(((Student) Model.loggedInUser).points + "/360 points completed");
            courseProgressBar.setValue(((Student) Model.loggedInUser).points);
            courseProgressBar.setEnabled(true);
            courseProgressBar.setVisible(true);
        }

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(userProfilePictureLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paperLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(myGradesLabel)
                    .addComponent(studentIDLabel)
                    .addComponent(studentCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(courseProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userProfilePictureLabel)
                .addGap(18, 18, 18)
                .addComponent(userNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTypeLabel)
                .addGap(32, 32, 32)
                .addComponent(studentIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myGradesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paperLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        if (Model.loggedInUser.getUserType().equals("Student") && ((Student) Model.loggedInUser).course != null) {
            studentCourseLabel.setText("<html>" + (Model.loggedInUser.getUserType().equals("Student") ? ((Student) Model.loggedInUser).course.getCourseName() : "") + "</html>");
        }
        if (Model.loggedInUser.getUserType().equals("Student")) {
            studentIDLabel.setText("Student ID: " + ((Student) Model.loggedInUser).getStudentID());
        }

        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 200, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        contentTabPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_homeButtonMouseExited

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setBackground(new Color(0,0,0,0));
        homeButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void personalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalDetailsButtonActionPerformed
        contentTabPane.setSelectedIndex(1);
    }//GEN-LAST:event_personalDetailsButtonActionPerformed

    private void personalDetailsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalDetailsButtonMouseExited
        personalDetailsButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_personalDetailsButtonMouseExited

    private void personalDetailsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalDetailsButtonMouseEntered
        personalDetailsButton.setBackground(new Color(0,0,0,0));
        personalDetailsButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_personalDetailsButtonMouseEntered

    private void academicDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academicDetailsButtonActionPerformed
        contentTabPane.setSelectedIndex(2);
    }//GEN-LAST:event_academicDetailsButtonActionPerformed

    private void academicDetailsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicDetailsButtonMouseExited
        academicDetailsButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_academicDetailsButtonMouseExited

    private void academicDetailsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicDetailsButtonMouseEntered
        academicDetailsButton.setBackground(new Color(0,0,0,0));
        academicDetailsButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_academicDetailsButtonMouseEntered

    private void enrolmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolmentButtonActionPerformed
        contentTabPane.setSelectedIndex(3);
    }//GEN-LAST:event_enrolmentButtonActionPerformed

    private void enrolmentButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolmentButtonMouseExited
        enrolmentButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_enrolmentButtonMouseExited

    private void enrolmentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolmentButtonMouseEntered
        enrolmentButton.setBackground(new Color(0,0,0,0));
        enrolmentButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_enrolmentButtonMouseEntered

    private void gradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradesButtonActionPerformed
        contentTabPane.setSelectedIndex(4);
    }//GEN-LAST:event_gradesButtonActionPerformed

    private void gradesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseExited
        gradesButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_gradesButtonMouseExited

    private void gradesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseEntered
        gradesButton.setBackground(new Color(0,0,0,0));
        gradesButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_gradesButtonMouseEntered

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog-wheel-silhouette-20px-hover.png")));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog-wheel-silhouette-20px.png")));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        new SettingsUI().setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-silhouette-20px-hover.png")));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-silhouette-20px.png")));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        logoutDialog.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonLogoutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonLogoutDialogActionPerformed
        try {
            AbstractUser.writeCurrentUserToDatabase();
        } catch (SQLException e) {
            System.err.println("SQL Error while writing users to database. See stack trace for more info.");
            e.printStackTrace();
        }
        logoutDialog.setVisible(false);
        logoutDialog.dispose();
        new LogInUI().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutButtonLogoutDialogActionPerformed

    private void cancelButtonLogoutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonLogoutDialogActionPerformed
        logoutDialog.setVisible(false);
        logoutDialog.dispose();
    }//GEN-LAST:event_cancelButtonLogoutDialogActionPerformed

    private void savePersonalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePersonalDetailsButtonActionPerformed
        Controller.updateUserData(
                new String[]{
                    firstNameField.getText(), 
                    lastNameField.getText(), 
                    personalEmailField.getText(), 
                    phoneNumberField.getText(), 
                    streetAdd1Field.getText(), 
                    streetAdd2Field.getText(), 
                    suburbField.getText(), 
                    cityField.getText(), 
                    postCodeField.getText()
                }
        );
        databaseSaveLabel.setForeground(Color.green);
        databaseSaveLabel.setText("Record saved successfully!");
    }//GEN-LAST:event_savePersonalDetailsButtonActionPerformed

    private void firstNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_firstNameFieldKeyPressed

    private void lastNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_lastNameFieldKeyPressed

    private void personalEmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personalEmailFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_personalEmailFieldKeyPressed

    private void phoneNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_phoneNumberFieldKeyPressed

    private void streetAdd1FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetAdd1FieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_streetAdd1FieldKeyPressed

    private void streetAdd2FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetAdd2FieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_streetAdd2FieldKeyPressed

    private void suburbFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suburbFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_suburbFieldKeyPressed

    private void cityFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_cityFieldKeyPressed

    private void postCodeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postCodeFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            savePersonalDetailsButtonActionPerformed(null);
        }
    }//GEN-LAST:event_postCodeFieldKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton academicDetailsButton;
    private javax.swing.JPanel academicDetailsPanel;
    private javax.swing.JButton cancelButtonLogoutDialog;
    private javax.swing.JTextField cityField;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTabbedPane contentTabPane;
    private javax.swing.JProgressBar courseProgressBar;
    private javax.swing.JLabel databaseSaveLabel;
    private javax.swing.JButton enrolmentButton;
    private javax.swing.JPanel enrolmentPanel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JButton gradesButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButtonLogoutDialog;
    private javax.swing.JDialog logoutDialog;
    private javax.swing.JLabel myGradesLabel;
    private javax.swing.JLabel paperLabel1;
    private javax.swing.JButton personalDetailsButton;
    private javax.swing.JPanel personalDetailsPanel;
    private javax.swing.JTextField personalEmailField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField postCodeField;
    private javax.swing.JButton savePersonalDetailsButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JTextField streetAdd1Field;
    private javax.swing.JTextField streetAdd2Field;
    private javax.swing.JLabel studentCourseLabel;
    private javax.swing.JLabel studentHubLogo;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField suburbField;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel userProfilePictureLabel;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
