/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jackdarlington.studenthub.ui;

import com.jackdarlington.studenthub.main.*;
import com.jackdarlington.studenthub.main.Model;

/**
 *
 * @author jack
 */
public class SettingsUI extends javax.swing.JFrame {

    /**
     * Creates new form SettingsUI
     */
    public SettingsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkedOrEmbedded = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        databaseSettingsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dbNameSettingsLabel = new javax.swing.JLabel();
        dbNameSettingsField = new javax.swing.JTextField();
        hostSettingsLabel = new javax.swing.JLabel();
        hostSettingsLabel.setVisible(false);
        hostSettingsField = new javax.swing.JTextField();
        hostSettingsField.setVisible(false);
        portSettingsLabel = new javax.swing.JLabel();
        portSettingsLabel.setVisible(false);
        portSettingsField = new javax.swing.JTextField();
        portSettingsField.setVisible(false);
        applicationCredentialsSettingsLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        userNameSettingsLabel = new javax.swing.JLabel();
        userNameSettingsField = new javax.swing.JTextField();
        passwordSettingsLabel = new javax.swing.JLabel();
        passwordSettingsField = new javax.swing.JTextField();
        networkedSettingsButton = new javax.swing.JRadioButton();
        embeddedSettingsButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setAlwaysOnTop(true);
        setMaximumSize(jPanel1.getMaximumSize());
        setMinimumSize(jPanel1.getMinimumSize());
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(309, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(309, 317));
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 317));

        databaseSettingsLabel.setText("Database");

        dbNameSettingsLabel.setText("Name");

        dbNameSettingsField.setText(Model.DB_NAME);
        dbNameSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbNameSettingsFieldActionPerformed(evt);
            }
        });

        hostSettingsLabel.setText("Host");

        hostSettingsField.setText(Model.URL);
        hostSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostSettingsFieldActionPerformed(evt);
            }
        });

        portSettingsLabel.setText("Port");

        portSettingsField.setText(Model.PORT);
        portSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portSettingsFieldActionPerformed(evt);
            }
        });

        applicationCredentialsSettingsLabel.setText("Application Credentials");

        userNameSettingsLabel.setText("User Name");

        userNameSettingsField.setText(Model.USER_NAME);
        userNameSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameSettingsFieldActionPerformed(evt);
            }
        });

        passwordSettingsLabel.setText("Password");

        passwordSettingsField.setText(Model.getPasswordCovered());
        passwordSettingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSettingsFieldActionPerformed(evt);
            }
        });

        networkedOrEmbedded.add(networkedSettingsButton);
        networkedSettingsButton.setText("Networked");
        networkedSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkedSettingsButtonActionPerformed(evt);
            }
        });

        networkedOrEmbedded.add(embeddedSettingsButton);
        embeddedSettingsButton.setSelected(true);
        embeddedSettingsButton.setText("Embedded");
        embeddedSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embeddedSettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(applicationCredentialsSettingsLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordSettingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userNameSettingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userNameSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(portSettingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(portSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(hostSettingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hostSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(dbNameSettingsLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dbNameSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(embeddedSettingsButton)
                            .addComponent(networkedSettingsButton)))
                    .addComponent(databaseSettingsLabel)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databaseSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(embeddedSettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkedSettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbNameSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbNameSettingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostSettingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portSettingsLabel))
                .addGap(34, 34, 34)
                .addComponent(applicationCredentialsSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameSettingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordSettingsLabel)
                    .addComponent(passwordSettingsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void embeddedSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embeddedSettingsButtonActionPerformed
        this.hostSettingsLabel.setVisible(false);
        this.hostSettingsField.setVisible(false);
        this.portSettingsLabel.setVisible(false);
        this.portSettingsField.setVisible(false);

    }//GEN-LAST:event_embeddedSettingsButtonActionPerformed

    private void networkedSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkedSettingsButtonActionPerformed
        this.hostSettingsLabel.setVisible(true);
        this.hostSettingsField.setVisible(true);
        this.portSettingsLabel.setVisible(true);
        this.portSettingsField.setVisible(true);
    }//GEN-LAST:event_networkedSettingsButtonActionPerformed

    private void passwordSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSettingsFieldActionPerformed

    private void userNameSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameSettingsFieldActionPerformed

    private void portSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portSettingsFieldActionPerformed

    private void hostSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostSettingsFieldActionPerformed

    private void dbNameSettingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbNameSettingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbNameSettingsFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Model.updateDBInformation(
            dbNameSettingsField.getText(), 
            hostSettingsField.getText(), 
            portSettingsField.getText(), 
            userNameSettingsField.getText(), 
            passwordSettingsField.getText()
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationCredentialsSettingsLabel;
    private javax.swing.JLabel databaseSettingsLabel;
    private javax.swing.JTextField dbNameSettingsField;
    private javax.swing.JLabel dbNameSettingsLabel;
    private javax.swing.JRadioButton embeddedSettingsButton;
    private javax.swing.JTextField hostSettingsField;
    private javax.swing.JLabel hostSettingsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup networkedOrEmbedded;
    private javax.swing.JRadioButton networkedSettingsButton;
    private javax.swing.JTextField passwordSettingsField;
    private javax.swing.JLabel passwordSettingsLabel;
    private javax.swing.JTextField portSettingsField;
    private javax.swing.JLabel portSettingsLabel;
    private javax.swing.JTextField userNameSettingsField;
    private javax.swing.JLabel userNameSettingsLabel;
    // End of variables declaration//GEN-END:variables
}
